# Chapter 1: Introduction to Measurement

-   Item Response Theory (IRT) / Latent Trait Theory / Item Characteristic Curve Theory

-   Measurement: the assignment of numerals to objects or events according to rules

-   IRT: variable we're measuring is considered to be continuous in nature

## Measurement

-   Variable or construct that cannot be observed : *latent* (example: anxiety)

-   Measurement process involves deciding whether a latent variable is conceptualized as categorical, continuous, or both

-   Categorical: persons differ from one another in kind on the latent variable - these latent **kinds** or categories are referred to as *latent classes*. *Latent Class Analysis* can be used to conceptualize the data. (example: has or doesn't have anxiety)

-   Continuous: individuals different from one another by the **quantity** of the latent variable. So we have ends to the *latent continuum* (high versus low). *Latent Trait Theory / IRT* can be used here.

-   Mix of Categorical and Continuous facets: two or more latent classes & one or more latent continua. The latent classes are subpopulations that are homogeneous with respect to the variable of interest but differ from one another in kind. With each of these classes there is a latent continuum on which the individuals within the class may be located. (Example: Class 1: severe anxiety ; Class 2: not sever anxiety + measure of anxiety quantity within each of those classes (continuum)) - *Mixture models* (e.g. mixture Rasch model) can b used here.

-   We cannot observe latent variables but their existence is observed using *manifest* variables. We use them to provide an *operational definition* of the latent variable.

-   Our interest is in the latent variable and its operational definition is a means to that end.

-   \(1\) conceptualization of latent variable nature + (2) operational definition

-   \(3\) is the correspondence between our observations of the individual's \[anxiety levels\] and their locations on the continuum and/or in a class - this is called scaling.

-   *Scaling*: the process of establishing the correspondence between the observation data and the person's location on the latent variable.

-   IRT is one approach to establishing this correspondence between the observation data and the persons' locations on the latent variable.

## Some Measurement Issues

-   Four measurement issues

-   \(1\) : *consistency of the measures \[reliability\]*

-   measurements with small amount of error have higher consistency / reliability

-   (2): *validity*

-   validity: degree to which our measures are actually manifestations of the latent variable

-   A necessary but not sufficient condition for measurements to have validity is that they posses a high degree of reliability. Therefore, it is necessary to be concerned not only with the consistency our measurements, but also with their validity. Obtaining validity evidence is part of the measurement process.

-   (3): *invariance*: Thurstone noted that a measuring instrument must not be seriously affecting in its measuring object by the object of measurement. In other words, we would like our measurement instrument to be independent of what it is we are measuring.

-   Example given about measuring a box by using a meter stick or by using a string to measure the shortest dimension and then cutting that string and then using that cut string to measure the other dimensions and getting their measures as multiples of that short cut string. Applying this approach to 2 different boxes for example would lead to measurements that cannot be compared to one another. The box we are measuring affects our measurement instrument and our measurements would not possess the invariance property. Without invariance, our comparisons across different boxes have limited utility.

-   (4): levels of measurement

-   Steven's levels of measurements or Coombs's taxonomy : measurements have certain inherent properties that affect how we interpret their information

-   *Ratio / Interval / Ordinal / Nominal*

## Item Response Theory

-   *theory:* paradigm that attempts to explain all the facts with which it can be confronted rather than in the traditional sense of explaining why a person provides a particular response to an item or how a person decides to answer (some have tried explanatory approaches though like Linear Logistic Test Model \[LLTM\]).

-   IRT uses latent characterizations of individuals and items as predictors of observed patterns

-   Cognitive processes used by an individual to respond to an item are not modeled in commonly used IRT models.

-   Similar to measuring the speed of an automatic mobile without understanding how an automobile moves.

-   In IRT, persons and items are located on the same continuum.

-   Most IRT models assume the latent variable is represented by an unidimensional continuum.

-   For an item to have any utility, it must be able to differentiate among persons located at different points along a continuum. This ability can be held constant or allowed to vary across instrument items.

-   Individuals are characterized in terms of their locations on the latent variable , and, at a minimum, items are characterized with respect to their locations and capacity to discriminate among persons.

-   The gist of IRT is the (logistic or multinational) regression of observed item responses \[DV\] on the persons' locations on the latent variable and the item's latent characterization(s) \[IVs\].

## Classical Test Theory

-   Classical Test Theory (CTT) or True Score Theory also (like IRT) assumes the latent variable to be continuous.

-   IRT: item is unit of focus ; CTT: observed score on whole instrument is unit of focus

-   Individual score $X$ is typically the unweighted sum of person's responses to individual items.

-   CTT is based on true score model : relates individual's observed score to their location on the latent variable

-   Assume you administer the instrument an infinite independent number of times. The mean of the observed scores is the expectation of the observed scores: $\mu_i=\varepsilon(X_i)$ . One any administration there will be an error (difference).

    $$ 
    X_i=\mu_i+E_i
    $$ {#eq-1}

-   $E_i$ is the error of measurement

-   @eq-1 is known as the true score model.

-   Given that the error scores are considered to be random and $\mu_i=\varepsilon(X_i)$ , then it follows that the mean error of an individual across all independent infinite administrations is zero.

-   $\mu_i$ is also represented by $T$ . $T$ represents the person's true score. Not meant to represent "truth", so we refer to it as trait score.

-   A person's trait score represents their location on the latent variable of interest and is fixed for an individual and instrument.

-   @eq-1 can also be represented as $$X_i=T_i+E_i$$ {#eq-2}

-   The IRT person latent trait $\theta$ and the CTT person trait characterization are related based on the assumption of parallel forms for an instrument. Note: **parallel forms** (also called **equivalent forms** or **alternate forms**) refer to two or more versions of a test that measure the same psychological construct with **equal difficulty and reliability.** So each item has the same response function on all the forms.

-   The expected proportions of 1s or the expected true score $\varepsilon (T)$ across the parallel forms is the average probability of a response of 1 on the instrument given the person's latent trait and an IRT model. So, the IRT $\theta$ is is the same as $\varepsilon (T)$ but has a different scale. The scale for $\varepsilon (T)$ is 0 to 1 but for $\theta$ it is $-\infty$ to $\infty$ . They are related by a monotonous increasing transformation.

-   3 assumptions for CTT : (1) the errors are uncorrelated with the trait score ; (2) the errors on one instrument are not correlated with the trait scores on a different instrument ; (3) the errors on one instrument are not correlated with the error scores on a different instrument. These are "weak" assumptions because they are likely to be met by data ; unlike the "strong" assumptions of IRT.

-   CTT assumptions + @eq-1 form the basis of the concepts or reliability and validity coefficient.

-   Index of reliability of a measurement: correlation of observed scores and trait scores

-   population reliability of instrument using variance of trait scores and observed scores: $$\rho_{XX'}= \frac{\sigma_T^2}{\sigma_X^2}$$ {#eq-3}

-   The trait score variance is unknown, so we can only estimate $\rho_{XX'}$ (example: coefficient alpha)

-   If you substitute $\sigma_T^2=\sigma_X^2-\sigma_E^2$ in @eq-3 , you get:

    $$\sigma_E^2=\sigma_X^2(1-\rho_{XX'})$$ {#eq-4}

-   Standard Error of Measurement (SEM) is the square root of $$\sigma_E^2$$ . It is the standard deviation of the errors of measurement associated with the observed scores.

-   Because the latent trait is unknown, so error is unknown, so @eq-1 and @eq-2 have two unknowns. This means that we cannot disprove them.

-   Unlike CTT, in IRT, we can engage in model-data fit analysis. In CTT, we assume the model to be true.

-   In CTT, person measurement is dependent on the instrument's characteristics. The heterogeneity or lack thereof of the observed scores affects the reliability an SEM.

-   @eq-3 and @eq-4 are not solely properties of the instrument, but are affected by the sample.

-   This means that Thurstone's idea of invariance does not exist in CTT. In contrast, in IRT, it is possible to have invariance of both person and item characterizations.

## Latent Class Analysis

-   In LCA, unlike IRT, the latent variable is assumed to be categorical.

-   The latent variable consists of a set of mutually exclusive and exhaustive latent classes.

-   The comparison of individuals involves comparing their latent class membership rather than their location on a continuous latent variable.

-   Mixture Models can conceive of situations where we have both latent classes and continuous continuum : LCA+IRT

-   Both LCA and IRT are cases of LSA (Latent Structure Analysis)

-   LCA determines the number of latent classes that best explains the data / latent class structure. This involves comparing models that vary by the number of classes.

-   Determining latent class structure is not only based on statistical tests of fit, but also interpretability of the solution.

-   relative sizes of classes is the latent class proportion : $$\pi_v$$

-   A latent class model with a sufficient number of latent classes is equivalent to an IRT

## Summary

-   Measurement is a process by which one attempts to understand the nature of a variable by applying mathematical techniques. This results may not be numeric labels and may not involve a continuous variable.

-   Manifest variable is an observed manifestation of one or more latent variables.

-   A latent variable can be conceptualized as continuous, categorical, or a combination of the two.

-   It is necessary to operationalize the variable(s) of interest \[i.e., provide operational definitions\] as part of the measurement process.

-   Measurement involves assessing how much information the measure yields about the participants (reliability) and how well the measure reflect the latent variable (i.e, validity).

-   When IRT is appropriate and there is model-data fit, IRT offers more advantages over CTT: person location estimates are invariant with respect to the instrument, precision of estimates is known at the individual level and not just at the group level, and and item parameters transcend the sample used in their estimation.
